### ISSUE TITLE
is there a way to preserve the original query string similar to base

### ISSUE THREAD

**Issue by wighawag** [pshrmn/hickory#74]
Not sure if it could also be solved in https://github.com/pshrmn/curi
but basically I have an application where user can append query string to set some global configuration option
While I can read these on the first page load, once user navigate to another page, the query string disapear and so when a user make a browser reload, the global configuration is gone.

Could hickory help somehow to handle this ?

Or should I manually keep track of the querystring param I am interested in keeping globaly and then append them to every page link to ensure they are preserved ?

**Comment by wighawag** [comment]
What I was thinking is that hickory could accept a set of query param, like the `base` param that would be added automatically.

something like:
```
{
  history: {
    base: "/root",
    baseQuery: [{name: "apiUrl", value: "http://localhost:8081"}, {debug: "true"}]
  }
}
```

Note I use array to ensure ordering determinism, but maybe this would be simpler:

`baseQuery: "?apiUrl=http://localhost:8081&debug=true"`

**Comment by pshrmn** [comment]
You could do this using a custom `query.stringify` function that always injects the params for you. For example, if you are using `qs`:

```ts
{
  history: {
    query: {
      parse: qs.parse,
      stringify(obj) {
        return qs.stringify({
          apiUrl: "http://localhost:8081",
          debug: true,
          ...obj
        });
      }
    }
  }
}
```
Please let me know if that works for you. The `query` is tricky because it can have a bunch of different types (string, object, `URLSearchParams`), so it will always require the user to specify how to inject the permanent params.

**Comment by wighawag** [comment]
great! it looks like it is working fine.
I used my own qs parser that do not cover all case as I want to limit the size of my app, but maybe gs is already bundled ?
I see it is used as a dev dependency but not sure if it is bundled

**Comment by pshrmn** [comment]
`qs` isn't bundled, I default to using that in examples since I think it is the most popular query parsing package.
